# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '2-5-8' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 2-5-8
pod 'Firebase/Analytics'

  target '2-5-8Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '2-5-8UITests' do
    # Pods for testing
  end

end
