# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '2-4-7' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 2-4-7
    pod 'TwitterKit'

  target '2-4-7Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '2-4-7UITests' do
    # Pods for testing
  end

end
